name: iirc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.6.1
  logging: ^1.0.2

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  mfsao: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
  remove_alpha_ios: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: i10n
