name: iirc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  clock: ^1.1.0
  cloud_firestore: ^3.4.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  faker: ^2.0.0
  firebase_analytics: ^9.2.1
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  google_sign_in: ^5.4.0
  intl: ^0.17.0
  intl_utils: ^2.6.1
  logging: ^1.0.2
  o_color_picker: ^1.0.2
  riverpod: ^1.0.3
  rxdart: ^0.27.4
  table_calendar: ^3.0.6

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  mfsao: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
  remove_alpha_ios: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: i10n
