name: iirc
description: If I remember correctly.
publish_to: 'none'
version: 1.4.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  clock: ^1.1.1
  cloud_firestore: ^4.3.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.0.0
  equatable: ^2.0.5
  faker: ^2.1.0
  firebase_analytics: ^10.0.8
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  logging: ^1.1.0
  meta: ^1.8.0
  o_color_picker: ^1.0.2
  package_info_plus: ^3.0.2
  platform: ^3.1.0
  riverpod: ^1.0.3
  rxdart: ^0.27.7
  sentry: ^6.15.1
  sliver_tools: ^0.2.8
  table_calendar: ^3.0.8
  universal_io: ^2.0.4
  uuid: ^3.0.7

dev_dependencies:
  build_runner:
  device_info_plus_platform_interface: ^7.0.0
  fake_async: ^1.3.1
  firebase_core_platform_interface:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  mfsao: ^3.0.0
  mocktail: ^0.3.0
  package_info_plus_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.1.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Thin.otf
          weight: 100
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
  remove_alpha_ios: true
