name: iirc
description: If I remember correctly.
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  clock: ^1.1.0
  cloud_firestore: ^3.4.5
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  faker: ^2.0.0
  firebase_analytics: ^9.3.2
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_crashlytics: ^2.8.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  google_sign_in: ^5.4.1
  intl: ^0.17.0
  intl_utils: ^2.7.0
  logging: ^1.0.2
  o_color_picker: ^1.0.2
  platform: ^3.1.0
  riverpod: ^1.0.3
  rxdart: ^0.27.5
  sliver_tools: ^0.2.7
  table_calendar: ^3.0.6
  universal_io: ^2.0.4
  uuid: ^3.0.6

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  mfsao: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Thin.otf
          weight: 100
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"
  remove_alpha_ios: true

flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: en
  arb_dir: l10n
