name: Format, Analyze and Test

on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - master
      - release/**

env:
  java_version: "12.x"
  flutter_version: "3.0.2"
  flutter_path: /opt/hostedtoolcache/flutter

jobs:
  default_run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.flutter_path }}
          key: ${{ runner.os }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed -l 120 lib
      - run: flutter packages pub run intl_utils:generate
      - run: flutter analyze lib
      - run: flutter test --no-pub --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
